name: Publish Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if gh-pages branch exists
        id: check
        run: |
          if git ls-remote --exit-code origin gh-pages &>/dev/null; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create .env.local file
        if: steps.check.outputs.exists == 'true'
        run: |
          echo "DATOCMS_PUBLISHED_CONTENT_CDA_TOKEN=${{ secrets.DATOCMS_PUBLISHED_CONTENT_CDA_TOKEN }}" >> .env.local
          echo "DATOCMS_DRAFT_CONTENT_CDA_TOKEN=${{ secrets.DATOCMS_DRAFT_CONTENT_CDA_TOKEN }}" >> .env.local

      - name: Setup Node.js
        if: steps.check.outputs.exists == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        if: steps.check.outputs.exists == 'true'
        run: npm ci

      - name: Build Storybook
        if: steps.check.outputs.exists == 'true'
        run: npm run build-storybook

      - name: Copy ignore-step.sh to Storybook output
        if: steps.check.outputs.exists == 'true'
        run: cp ignore-step.sh storybook-static/

      - name: Add .nojekyll file
        run: touch storybook-static/.nojekyll

      - name: Deploy Storybook to GitHub Pages
        if: steps.check.outputs.exists == 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}
