name: Initialize Repo

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      env_file:
        description: Paste your .env values here.
        required: true
        # TODO: Remove default
        default: DATOCMS_DRAFT_CONTENT_CDA_TOKEN=95467ff63af3df6df1d0c302026882 DATOCMS_PUBLISHED_CONTENT_CDA_TOKEN=dd745772bd47b1e8374321d9be4f72 DATOCMS_CMA_TOKEN=65a48319c1da9eba0d8e2793047755 SITE_URL=http://localhost:3000
      website_url:
        description: Public URL of the deployed Vercel site.
        required: true
        # TODO: Remove default
        default: https://test.vercel.app

# TODO: Add an input for the PAT instead of relying on the actions secrets.

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Create secret environment variables from inputs (safely)
        run: |
          ENV_FILE=$(jq -r '.inputs.env_file' "$GITHUB_EVENT_PATH")
          WEBSITE_URL=$(jq -r '.inputs.website_url' "$GITHUB_EVENT_PATH")

          # Mask full input values
          echo "::add-mask::$ENV_FILE"
          echo "::add-mask::$WEBSITE_URL"

          # Export as environment variables for later steps
          echo "ENV_FILE=$ENV_FILE" >> $GITHUB_ENV
          echo "WEBSITE_URL=$WEBSITE_URL" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required CLI tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Run initialization script
        env:
          GH_TOKEN: ${{ secrets.REPO_ADMIN_PAT }}
        run: |
          bash scripts/initialize-repo.sh \
            "${{ github.repository_owner }}" \
            "${{ github.event.repository.name }}" \
            "${{ secrets.REPO_ADMIN_PAT }}" \
            "$ENV_FILE" \
            "$WEBSITE_URL"