name: Initialize Repo

on:
  workflow_dispatch:
    inputs:
      env_file:
        description: Paste your .env values here.
        required: true
      website_url:
        description: Public URL of the deployed Vercel site.
        required: true

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install required CLI tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Mask values from input
        run: |
          echo "${{ github.event.inputs.env_file }}" | tr ' ' '\n' | grep '=' | cut -d= -f2- | while read val; do
            echo "::add-mask::$val"
          done

      - name: Run initialization script
        env:
          GH_TOKEN: ${{ secrets.REPO_ADMIN_PAT }}
        run: |
          bash scripts/initialize-repo.sh \
            "${{ github.repository_owner }}" \
            "${{ github.event.repository.name }}" \
            "${{ secrets.REPO_ADMIN_PAT }}" \
            "${{ github.event.inputs.env_file }}" \
            "${{ github.event.inputs.website_url }}"