name: Spell Check

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  spellcheck:
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies & Generate Types (thanks to `prepare` script in `package.json`)
        env:
          DATOCMS_PUBLISHED_CONTENT_CDA_TOKEN: ${{ secrets.DATOCMS_PUBLISHED_CONTENT_CDA_TOKEN }}
        run: npm ci

      - name: Run Spell Check
        run: npm run spellcheck